---
- hosts: all
  become: yes
  vars:
    - pkg: apache2
    - pkg1: httpd
  tasks:
  - name: installing "{{pkg}}"
    package: 
        name:  "{{pkg}}"
        state: present
        update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: installing "{{pkg1}}"
    package:
        name:  "{{pkg1}}"
        state: present
    notify: start service "{{pkg1}}"
    when: ansible_distribution == "RedHat"
   
  - name: copying
    copy:
        src: index.html
        dest: /var/www/html/index.html
    notify: start service "{{pkg1}}"

  handlers:
  - name: start service "{{pkg1}}"
    service: 
       name: "{{pkg1}}"
       state: reloaded

